### ISSUE TITLE
Modprobe not working for sc16is7xx

### ISSUE THREAD

**Issue by Tambup** [Avnet/raspberrypi-industrial-gateway#11]
Using the v1.3 [here](www.element14.com/community/docs/DOC-92862) the sc16is7xx is not loaded by default.
Using the modprobe command is not adding the sc16is7xx driver in any way; instead the use of insmod is working.

We guess that the driver is not loadad due to some error executing modprobe during startup.

The "manual" use of insmod solved the problem, but is not straightforward for an industrial device.

**Comment by NicolasBesson** [comment]
> sc16is7xx

Loading the serial kernel module can be performed using : 
`insmod /lib/modules/4.14.79-v7+/kernel/drivers/tty/serial/sc16is7xx.ko`

Nicolas

**Comment by Tambup** [comment]
> > sc16is7xx
> 
> Loading the serial kernel module can be performed using :
> `insmod /lib/modules/4.14.79-v7+/kernel/drivers/tty/serial/sc16is7xx.ko`
> 
> Nicolas

Yes, we solved in this way.
Btw rebuilding or edit the version provided would be a better solution.

We hope the developers fix this problem soon.

**Comment by wsradcliffe** [comment]
Thanks for bringing this to our attention.

To fix this issue, the kernel/modules have been rebuilt and included in an updated image: avtse-iiotg-v13a-20210228.zip

You can find the released image by going to the landing page: element14.com/gateway then clicking on the "Software Image" resource link.

**Comment by Tambup** [comment]
Perfect. Thanks for support.
