### ISSUE TITLE
Only one init per module

### ISSUE THREAD

**Issue by ledvinap** [Avnet/raspberrypi-industrial-gateway#2]
Hello,
spi-bcm2835aux.c
https://github.com/Avnet/smartedge-iiot-gateway/blob/d103e5f98afd3f7b6c1af8081e1e13a13eeef077/drivers/spi/spi-bcm2835aux.c#L545-L546 uses both `module_platform_driver` and `arch_initcall`, failing during compilation (as module).

Removing `arch_initcall` (and empty `bcm2835aux_init`) fixes this problem ...

**Comment by WaynePetersIot** [comment]
This can not be compiled as a module because early boot requires this built into kernel so TPM can be correctly accessed.  Do not compile as a module.
